//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CardGame_v2Entities : DbContext
    {
        public CardGame_v2Entities()
            : base("name=CardGame_v2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Card> tblCard { get; set; }
        public virtual DbSet<CardPack> tblCardPack { get; set; }
        public virtual DbSet<CardType> tblCardType { get; set; }
        public virtual DbSet<Deck> tblDeck { get; set; }
        public virtual DbSet<DeckCard> tblDeckCard { get; set; }
        public virtual DbSet<User> tblUser { get; set; }
        public virtual DbSet<UserCardCollection> tblUserCardCollection { get; set; }
        public virtual DbSet<UserRole> tblUserRole { get; set; }
        public virtual DbSet<VirtualPurchase> tblVirtualPurchase { get; set; }
    }
}
