//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRanking
    {
        public int ID { get; set; }
        public int pack_id { get; set; }
        public Nullable<short> rating { get; set; }
        public int user_id { get; set; }
    
        public virtual CardPack tblCardPack { get; set; }
        public virtual User tblUser { get; set; }
    }
}
