//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AllDecks = new HashSet<Deck>();
            this.AllUserCardCollections = new HashSet<UserCardCollection>();
            this.AllVirtualPurchase = new HashSet<VirtualPurchase>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mail { get; set; }
        public string GamerTag { get; set; }
        public byte[] Password { get; set; }
        public string UserSalt { get; set; }
        public Nullable<int> ID_UserRole { get; set; }
        public byte[] Avatar { get; set; }
        public int AmountMoney { get; set; }
        public string Street { get; set; }
        public Nullable<int> Streetnumber { get; set; }
        public string Post_Code { get; set; }
        public string City { get; set; }
        public Nullable<System.Guid> activationCode { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deck> AllDecks { get; set; }
        public virtual UserRole UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCardCollection> AllUserCardCollections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VirtualPurchase> AllVirtualPurchase { get; set; }
    }
}
